# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mend < Formula
  desc "Repository health and quality checker"
  homepage "https://github.com/toaweme/mend"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_darwin_x64.tar.gz"
      sha256 "a851b945e84772f539dfab25c59cfa19ffbeca9502df18427d2ea01ea00edb09"

      define_method(:install) do
        bin.install "mend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_darwin_arm64.tar.gz"
      sha256 "5bdf4eb70ae4ed28e4fe957be3a54a3cd1349578a8e064d2fd810f0b78a6a9fa"

      define_method(:install) do
        bin.install "mend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_linux_x64.tar.gz"
      sha256 "02a0c34278ffb7efa12173aa8e55e01375d9fa7bc3dbd7b11a3ef2581af0b50f"
      define_method(:install) do
        bin.install "mend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_linux_arm64.tar.gz"
      sha256 "a1b62684322e3a32416b82691cf97c25ed0d7d3441040f6c04dfe559e4503c1c"
      define_method(:install) do
        bin.install "mend"
      end
    end
  end

  test do
    system "#{bin}/mend", "--help"
  end
end
