# This file was generated by GoReleaser. DO NOT EDIT.
cask "blink" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "db3f27c4e73ad8bda1a24c9a13007114fb0903923d77faa73e511f6ffe4600e8"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_darwin_x64.tar.gz"
    end
    on_arm do
      sha256 "5674e2101be91adced930194364b514735c3a63f88b1684587fdc565467d500c"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e50012b9e56798250195297b7b13c8e0b170465eb8ddba1ecbde8392d597d4d3"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_linux_x64.tar.gz"
    end
    on_arm do
      sha256 "ad4eb0e5a30c585066ff928240de8f2ab07ca3d085ccf77d3954b0ec5b0f9767"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_linux_arm64.tar.gz"
    end
  end

  name "blink"
  desc "Live-reload supervisor for local dev"
  homepage "https://github.com/toaweme/blink"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blink"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blink"]
    end
  end

  # No zap stanza required

end
