# This file was generated by GoReleaser. DO NOT EDIT.
cask "blink" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "8c47201acecfdd97549cf803bcffdaf3cf52a51961aea886e47ede3a206d99df"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_darwin_x64.tar.gz"
    end
    on_arm do
      sha256 "bc7a7ec00853733400a441603e7de03605a60c7f4f6e1349ac4d370490230c0f"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bee89099353137c65a501169d41eea897ad0ecb39a17bebad613f3f78092488a"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_linux_x64.tar.gz"
    end
    on_arm do
      sha256 "c9e5cfed4a50c9e998dfa5bd76a4aa726d32de3b3f80c01636cb476185c0e76c"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_linux_arm64.tar.gz"
    end
  end

  name "blink"
  desc "Live-reload supervisor for local dev"
  homepage "https://github.com/toaweme/blink"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blink"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blink"]
    end
  end

  # No zap stanza required

end
