# This file was generated by GoReleaser. DO NOT EDIT.
cask "blink" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "bc3b7bcfe9d7c0b36caac0d808c1764884dd289cf285ab3b5e87ba19a0caadb1"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_darwin_x64.tar.gz"
    end
    on_arm do
      sha256 "205d29580c0a3c4cd87caac3a375e7910cbec5b936b4b65b85c66abf6ddc8eea"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88ce9866966ea15fe2aadaadeedfab4c35441cd90bc7576c598a0364d1a2691c"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_linux_x64.tar.gz"
    end
    on_arm do
      sha256 "fb07b1079bb1891ab8341400d334cb0a9c0465709cf7dceeaca5c2625dfea914"
      url "https://github.com/toaweme/blink/releases/download/v#{version}/blink_#{version}_linux_arm64.tar.gz"
    end
  end

  name "blink"
  desc "Live-reload supervisor for local dev"
  homepage "https://github.com/toaweme/blink"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blink"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blink"]
    end
  end

  # No zap stanza required

end
