# This file was generated by GoReleaser. DO NOT EDIT.
cask "care" do
  version "0.9.5"

  on_macos do
    on_arm do
      sha256 "1ea144d38e1b22d75037cf6c7a20c6cb88459ac4e2147b54a015a5cd312f7cbe"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "20b57a60737f12481063dd6bb42a6791b11c503d8ac41699e03fcf1c5be8f93c"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_darwin_x64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9c3f2cb212fcdf9e2e417b455631f1edc53f35f339fa552ea6b5a2e29f0af5d9"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "66f190e67eff47e4ddeb2c2ea0e4946a711739c01f675cd48af2f1f9c43f0a36"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_linux_x64.tar.gz"
    end
  end

  name "care"
  desc "Repository health and quality checker"
  homepage "https://github.com/toaweme/care"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "care"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/care"]
    end
  end

  # No zap stanza required
end
