# This file was generated by GoReleaser. DO NOT EDIT.
cask "care" do
  version "0.9.4"

  on_macos do
    on_intel do
      sha256 "4ca6499bbcdced40ed9bf29c85990f3448c0be1ce406913b1cb9114dcfb90309"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_darwin_x64.tar.gz"
    end
    on_arm do
      sha256 "0f2ff31142357b742037b59c1536ea2de5fb1985d863d2516211360fb0df6d36"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f43f76ec9dd305fb5bbfaacf1dd742f48d518f9dd933eddaec48febf2b74a260"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_linux_x64.tar.gz"
    end
    on_arm do
      sha256 "3e3c128a5bf0a851e87beb5bfc142a78501d06d558020acab3ddaadcd6fd292a"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_linux_arm64.tar.gz"
    end
  end

  name "care"
  desc "Repository health and quality checker"
  homepage "https://github.com/toaweme/care"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "care"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/care"]
    end
  end

  # No zap stanza required

end
