# This file was generated by GoReleaser. DO NOT EDIT.
cask "care" do
  version "0.9.6"

  on_macos do
    on_arm do
      sha256 "5e12b6f1f7b1401291f9bc477b7b2a6d44032d9d463da5843b299287f0017d94"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f8a67a9c01e3877671f4247040ededb74aa00710428917cde702c53df4b1479"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_darwin_x64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c7d6d67dd6057285e1e6fa10fa00752d7336b0cda3794700e508527cfdd3b7e0"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ac2f15994d26650ffccb567622521af031ee7809f6393914ef3cb7de1b29623a"
      url "https://github.com/toaweme/care/releases/download/v#{version}/care_#{version}_linux_x64.tar.gz"
    end
  end

  name "care"
  desc "Repository health and quality checker"
  homepage "https://github.com/toaweme/care"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "care"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/care"]
    end
  end

  # No zap stanza required
end
