# This file was generated by GoReleaser. DO NOT EDIT.
cask "codeview" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "4f2afc85085203dd35f3470a708dbed3f4c6c12f2bd7b1791b33cac15a89f091"
      url "https://github.com/toaweme/codeview/releases/download/v#{version}/codeview_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc8c9182b3b643355676b315055c4db6964a70dc3c63857ccf6a80397c1285b2"
      url "https://github.com/toaweme/codeview/releases/download/v#{version}/codeview_#{version}_darwin_x64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "45e88a0543c4ba8a2d227120d3557fed5f4a2e4048f5ae7623775c2de8154f20"
      url "https://github.com/toaweme/codeview/releases/download/v#{version}/codeview_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "79764d5ed495fbead8e08fabdf462bdf9e4f16820e3784b72d3f1a8c508a0919"
      url "https://github.com/toaweme/codeview/releases/download/v#{version}/codeview_#{version}_linux_x64.tar.gz"
    end
  end

  name "codeview"
  desc "Read-only web UI for git repositories"
  homepage "https://github.com/toaweme/codeview"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeview"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codeview"]
    end
  end

  # No zap stanza required
end
