# This file was generated by GoReleaser. DO NOT EDIT.
cask "codeview" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "6571596c530938a040d740eed94d295b85bd1e9ad23e4eb419d5b6f374631644"
      url "https://github.com/toaweme/codeview/releases/download/v#{version}/codeview_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "79ca269c8f5b72d15df80a4378491e8a81dad4433f647adbe32948d616c13cd4"
      url "https://github.com/toaweme/codeview/releases/download/v#{version}/codeview_#{version}_darwin_x64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "46dbef8caa166c48c1437711afe0943277452609b185906ab4bd08fe5a1aa4fe"
      url "https://github.com/toaweme/codeview/releases/download/v#{version}/codeview_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d68aed9d79165180f38622414cc2b799f4d5f6ce7c4a80e262ac4c6efb0498d"
      url "https://github.com/toaweme/codeview/releases/download/v#{version}/codeview_#{version}_linux_x64.tar.gz"
    end
  end

  name "codeview"
  desc "Read-only web UI for git repositories"
  homepage "https://github.com/toaweme/codeview"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeview"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codeview"]
    end
  end

  # No zap stanza required
end
