# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blink < Formula
  desc "Live-reload supervisor for local dev"
  homepage "https://github.com/toaweme/blink"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toaweme/blink/releases/download/v0.1.0/blink_0.1.0_darwin_x64.tar.gz"
      sha256 "6efe4726956237d15ff199ceee44a2b6c12cfee0a419cf2a093dbdb9849b4642"

      define_method(:install) do
        bin.install "blink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toaweme/blink/releases/download/v0.1.0/blink_0.1.0_darwin_arm64.tar.gz"
      sha256 "b5a38ac6b279f00dabea88a72c2f9a5138f7c46bbca167eb6ba298b2bb99dc1b"

      define_method(:install) do
        bin.install "blink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/blink/releases/download/v0.1.0/blink_0.1.0_linux_x64.tar.gz"
      sha256 "7d2c0b2b768ba7303c5d1933bef4d5eb9060873ef7c0240ebc8e3d3e6b71e21c"
      define_method(:install) do
        bin.install "blink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/blink/releases/download/v0.1.0/blink_0.1.0_linux_arm64.tar.gz"
      sha256 "e1eab9f37f4bfea820be82d95a1f4f1fd349a4928487e3c37e443a909e391ef7"
      define_method(:install) do
        bin.install "blink"
      end
    end
  end

  test do
    system "#{bin}/blink", "--help"
  end
end
