# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blink < Formula
  desc "Live-reload supervisor for local dev"
  homepage "https://github.com/toaweme/blink"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toaweme/blink/releases/download/v0.1.1/blink_0.1.1_darwin_x64.tar.gz"
      sha256 "ce547ed65d4300f789430418c5a51172a82dd9fc2477a6288ec52d38765c5d30"

      define_method(:install) do
        bin.install "blink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toaweme/blink/releases/download/v0.1.1/blink_0.1.1_darwin_arm64.tar.gz"
      sha256 "f7931cbc3e93f4d6a1cf31071e4024b427f97aa37ada9e5767034c86221acb9b"

      define_method(:install) do
        bin.install "blink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/blink/releases/download/v0.1.1/blink_0.1.1_linux_x64.tar.gz"
      sha256 "217ceb72d021279c31caa5b0a521c6b075027bac80360630cf9f307b67c27c4a"
      define_method(:install) do
        bin.install "blink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/blink/releases/download/v0.1.1/blink_0.1.1_linux_arm64.tar.gz"
      sha256 "07ba95495750cf45afe43120e19d911babbf76db48f5be9c34e08ddcf0794350"
      define_method(:install) do
        bin.install "blink"
      end
    end
  end

  test do
    system "#{bin}/blink", "--help"
  end
end
