# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Care < Formula
  desc "Repository health and quality checker"
  homepage "https://github.com/toaweme/care"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toaweme/care/releases/download/v0.8.0/care_0.8.0_darwin_x64.tar.gz"
      sha256 "75ca93adb0a1f04061ff5fc98f4996b9a9f0221efe75277fea7b38cbe90b7736"

      define_method(:install) do
        bin.install "care"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toaweme/care/releases/download/v0.8.0/care_0.8.0_darwin_arm64.tar.gz"
      sha256 "dff38bf914e6d1a0a1b60a0da17914131686de6152abaac1b74e6b5db7257912"

      define_method(:install) do
        bin.install "care"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/care/releases/download/v0.8.0/care_0.8.0_linux_x64.tar.gz"
      sha256 "785e3640a1272001cde8cf4b7eebd0d89fa45635bc939fbd368eafa26910a5fa"
      define_method(:install) do
        bin.install "care"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/care/releases/download/v0.8.0/care_0.8.0_linux_arm64.tar.gz"
      sha256 "919727a5dfeb7a39e0b0133e288be1ff744d450552d91a459c33d09fa4b57412"
      define_method(:install) do
        bin.install "care"
      end
    end
  end

  test do
    system "#{bin}/care", "--help"
  end
end
