# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Care < Formula
  desc "Repository health and quality checker"
  homepage "https://github.com/toaweme/care"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toaweme/care/releases/download/v0.3.0/care_0.3.0_darwin_x64.tar.gz"
      sha256 "ffb47fa46d9fcb27c1f1286ce108c090caf0acab9c0bf26d9e7b401862982376"

      define_method(:install) do
        bin.install "care"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toaweme/care/releases/download/v0.3.0/care_0.3.0_darwin_arm64.tar.gz"
      sha256 "8977ad44f464eab8e49d3f8b5ff34b5cf6f1098154ebbad561bab2321ea45257"

      define_method(:install) do
        bin.install "care"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/care/releases/download/v0.3.0/care_0.3.0_linux_x64.tar.gz"
      sha256 "4f73f98b81b337e8c57d65a7144bf44295365737f9453fda975b02f96cbd1c6e"
      define_method(:install) do
        bin.install "care"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/care/releases/download/v0.3.0/care_0.3.0_linux_arm64.tar.gz"
      sha256 "e4806025b6a3a02aa1712238ab104a5ec215ba8093f9589131c2ae0f2e91b709"
      define_method(:install) do
        bin.install "care"
      end
    end
  end

  test do
    system "#{bin}/care", "--help"
  end
end
