# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mend < Formula
  desc "Repository health and quality checker"
  homepage "https://github.com/toaweme/mend"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_darwin_x64.tar.gz"
      sha256 "19a506b3aed2b5fde7f2d9b24a43566ddb4928020efa412af5ca2fcfc88aa8ae"

      define_method(:install) do
        bin.install "mend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_darwin_arm64.tar.gz"
      sha256 "49966dd4e5acf0c9b765312f82affad4e739f2d3901aba0f5583256ad297b1e0"

      define_method(:install) do
        bin.install "mend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_linux_x64.tar.gz"
      sha256 "62af3e59914d3e8c552e4c8c1d0c8f7b9a6c81c9707b5bbd1e4d1b0c735784c4"
      define_method(:install) do
        bin.install "mend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_linux_arm64.tar.gz"
      sha256 "985f77be93e51a5c832aa638fa6a7941128be5166afa249ed6e667fbbca5da69"
      define_method(:install) do
        bin.install "mend"
      end
    end
  end

  test do
    system "#{bin}/mend", "--help"
  end
end
