# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mend < Formula
  desc "Repository health and quality checker"
  homepage "https://github.com/toaweme/mend"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_darwin_x64.tar.gz"
      sha256 "271dba07eef783754e323533081cfaecbd412c6679eca867bbca27cd54d5d412"

      define_method(:install) do
        bin.install "mend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_darwin_arm64.tar.gz"
      sha256 "be2c8f96cd5064824316236660d3647d93bfa03ccbd5b1865cc461b1a6f239e7"

      define_method(:install) do
        bin.install "mend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_linux_x64.tar.gz"
      sha256 "ecff05d5e806792799409cb7fda164755c86118b1076d01614624f27b71750e8"
      define_method(:install) do
        bin.install "mend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_linux_arm64.tar.gz"
      sha256 "28955af32d56e9e1646bd962befcefbe55aea4fc1c20445cc9c8d8bfc2ff3e28"
      define_method(:install) do
        bin.install "mend"
      end
    end
  end

  test do
    system "#{bin}/mend", "--help"
  end
end
