# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mend < Formula
  desc "Repository health and quality checker"
  homepage "https://github.com/toaweme/mend"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_darwin_x64.tar.gz"
      sha256 "4fea07ccf33c5dcccc7f25fd1b8af8919f9aa3ba689fdc4de35ffcc2988452fa"

      define_method(:install) do
        bin.install "mend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_darwin_arm64.tar.gz"
      sha256 "89756fc43ef40adc63b7df7d823ef2a1a45ac68ac5ce496f6f65bc35c513b353"

      define_method(:install) do
        bin.install "mend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_linux_x64.tar.gz"
      sha256 "a37126f5568681e5ae794682513080fc61d8a75848db63940121e7daafecd0da"
      define_method(:install) do
        bin.install "mend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toaweme/mend/releases/download/v0.1.0/mend_0.1.0_linux_arm64.tar.gz"
      sha256 "ccfcd55e6d21b61def1351d14ef10c5c2bdbab3db1183e7519336184d32a864b"
      define_method(:install) do
        bin.install "mend"
      end
    end
  end

  test do
    system "#{bin}/mend", "--help"
  end
end
